version: '3.6'

services:
    php:
        container_name: lab-php
        build:
            context: ./php
        networks:
            - lab
        depends_on:
            - mariadb
        volumes:
            - ./php/src:/var/www/html/
            - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    
    nginx:
        image: nginx:alpine
        container_name: lab-nginx
        depends_on:
            - php
        networks:
            - lab
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./php/src:/var/www/html/
            - ./nginx/conf.d/:/etc/nginx/conf.d/
    
    mariadb:
        image: mariadb
        container_name: lab-mariadb
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Rome
            - 'MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}'
            - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
            - 'MYSQL_USER=${MYSQL_USER}'
            - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
        volumes:
            - './mariadb_data:/var/lib/mysql/'
        networks:
            - lab
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: lab-phpmyadmin
        depends_on:
            - mariadb
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mariadb
            - PMA_PORT=3306
            - 'MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}'
            - 'MYSQL_USERNAME=${MYSQL_USER}'
        ports:
            - '8080:80'
        networks:
            - lab


networks:
    lab:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.2.0/24
