version: '3.6'

services:
    php:
        container_name: lab-php
        build:
            context: ./php
        networks:
            - lab
        volumes:
            - ./php/src:/var/www/html/
            - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    
    nginx:
        image: nginx:alpine
        container_name: lab-nginx
        depends_on:
            - php
        networks:
            - lab
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./php/src:/var/www/html/
            - ./nginx/conf.d/:/etc/nginx/conf.d/
    
    postgres:
        image: postgres:alpine
        container_name: lab-postgres
        environment:
            - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
            - 'POSTGRES_USER=${POSTGRES_USER}'
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - lab

volumes:
    postgres-data:

networks:
    lab:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.4.0/24
